spring.application.name=MsBookPayments
server.port=7171

#CONFIG Eureka Server
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://127.0.0.1:8761/eureka}
eureka.instance.prefer-ip-address=true
eureka.client.instance.leaseRenewalIntervalInSeconds=10
eureka.client.instance.leaseExpirationDurationInSeconds=30
#end config

#CONFIG microservicio buscador de libros
app.microservice.endpoint.searchBooks=${MS_SEARCH_BOOK:http://MS-BOOKS-CATALOGUE/libros/}
app.microservice.endpoint.saveStockBooks=${MS_SEARCH_BOOK:http://MS-BOOKS-CATALOGUE/libros/}
#end config

#CONFIG CLOUD
spring.cloud.config.enabled=false
#end config


#CONFIG DATABASE DEV
spring.datasource.url=jdbc:h2:mem:bookpayments_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
#end config

#CONFIG DATABASE PROD
#spring.datasource.url=jdbc:postgresql://localhost:5432/booksdb
#spring.datasource.username=postgres
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#end config

#CONFIG endpoints for actuator
management.endpoints.web.exposure.include=info,health
#access free for actuator
management.endpoint.health.show-details=always
management.endpoints.web.request-handler.predicate=/actuator/**
#info
info.app.name=MsBooksCatalogue Services
info.app.version=1.0.0
info.app.description=Encargado de acceder y tratar con la base de datos de relatos de papel.
#end config
